apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-producer
  name: location-producer
spec:
  ports:
  - name: 'producer'
    port: 50051
    targetPort: 50051
    nodePort: 30004
  selector:
    service: location-producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-producer
  name: location-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-producer
  template:
    metadata:
      labels:
        service: location-producer
    spec:
      containers:
      - name: location-producer
        image: bert69/location-producer:v1.3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
