apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-consumer
  name: location-consumer
spec:
  ports:
  - name: "consumer"
    port: 5005
    targetPort: 5005
    nodePort: 30010
  selector:
    service: location-consumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-consumer
  template:
    metadata:
      labels:
        app: location-consumer
    spec:
      containers:
        - name: location-consumer
          image: bert69/location-consumer:v1.2.2
          env:
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: DB_NAME
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: DB_PORT