openapi: "3.1.1"
info:
  title: Persons API
  version: "1.0.0"
  description: API for managing persons

servers:
  - url: "http://localhost:30001"
    description: Development server

paths:
  /persons:
    post:
      summary: Create a new person
      requestBody:
        description: Person object that needs to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        201:
          description: Person created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        404:
          description: 'Bad Request Invalid input, object invalid'

    get:
      summary: Retrieve all Persons.
      responses:
        200:
          description: List of Persons retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
        400:
             description: 'Invalid input, no such path'


  /persons/{person_id}:
    get:
      summary: Retrieve a person by ID
      parameters:
        - name: person_id
          in: path
          description: Unique ID for existing person
          required: true
          schema:
            type: string
      responses:
        200:
          description: Person retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'

components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier
          example: 345
        first_name:
          type: string
          description: First name of Person
          example: Bart
        last_name:
          type: string
          description: Last name of person
          example: Simpson
        company_name:
          type: string
          description: Company name of person
          example: Burns Enterprise
      required:
        - first_name
        - last_name
        - company_name
